### PR TITLE
Add `OffsetStart`

### PR DESCRIPTION
**Pull request by darsnack**
Adds `OffsetStart` which allows starting a schedule after a fixed offset. For example, `OffsetStart(Triangle(2, 10), 5)` will start after a half period of 5.

### CODE REVIEW

**Comment by darsnack** [comment]
@rejuvyesh is this what you need? Do you have a better name than `OffsetStart`...I kind of hate it.

**Comment by rejuvyesh** [comment]
`ShiftStart` seems no better a name. Functionality looks correct to me.

**Comment by rafaelorozco** [comment]
Could this be used to implement a "warm up" start? Such offsetting the start of your "real" optimizer while a linear increasing optimizer warms up the learning rate from 0 to the starting rate of the real optimizer?

**Comment by darsnack** [comment]
> ShiftStart seems no better a name. Functionality looks correct to me.

Okay, I think I'll go with `Shifted` as in a "shifted schedule."

> Could this be used to implement a "warm up" start? Such offsetting the start of your "real" optimizer while a linear increasing optimizer warms up the learning rate from 0 to the starting rate of the real optimizer?

Depending on what you want, it could certainly be useful, but it sounds like what you want can already be done.

```julia
# I am using Exp(initial_lr, decay) as an example
schedule = Sequence(Triangle(initial_lr, 2 * warmup_iters) => warmup_iters,
                    Exp(initial_lr, decay) => total_iters)
```

We basically run 1/2 a period of `Triangle` to get our linear ramp, then apply our schedule that we want. `Sequence` will start the `Exp` at `t = 1` when the overall iteration step is `warmup_iters + 1` (so it's like concatenating schedules all starting at the first iteration). `Shifted` would help if you wanted `Exp` to start at something other than `t = 1` when the overall iteration is `warmup_iters + 1`.

**Comment by darsnack** [comment]
@rafaelorozco I was only thinking of schedules that start at the initial LR like `Exp`. Some do not start at the peak, and you do need `Shifted` for those! So, I added a tutorial to the docs that explains this better.

**Pull request merged**
