### PR TITLE
Treat Flux dependency as an Extension 

### PR DESCRIPTION
**Pull request by maximilian-gelbrecht**
I made an attempt at #52 by adding a Flux extension. 

However, it is not quite working yet. I don't quite know why, so maybe somebody can help. The extension is not correctly loaded, the `Scheduler` struct can't be found, and neither the extension itself. Information on the extension system is a bit short right now as it is still quite new. I am not quite sure what is missing, as I thought that editing the `Project.toml` appropriately should be enough.

### CODE REVIEW

**Comment by ToucheSir** [comment]
Generally speaking, extensions should not be defining new public structs and functions. That may have something to do with the issue you're running into. Thankfully, I don't believe any extension-specific definitions are required here other than overriding the relevant Flux methods.

**Comment by darsnack** [comment]
The main issue is that you are not `using Flux` in the test script. That's why the extension is not being loaded.

Though Brian brings up a good point about where the struct should be defined. I think in this case, since it is not exported already, it is okay to define it within the extension only. But we should continue not to export it.

**Comment by maximilian-gelbrecht** [comment]
> The main issue is that you are not `using Flux` in the test script. That's why the extension is not being loaded.
> 
> Though Brian brings up a good point about where the struct should be defined. I think in this case, since it is not exported already, it is okay to define it within the extension only. But we should continue not to export it.

The test does load `Flux` though, in the same place as before that didn't change, or am I misunderstanding?  https://github.com/FluxML/ParameterSchedulers.jl/blob/c6ba671c08cc2c95dd6c0f1b27ab4f927b22c912/test/runtests.jl#L2

> Generally speaking, extensions should not be defining new public structs and functions. That may have something to do 
> with the issue you're running into. Thankfully, I don't believe any extension-specific definitions are required here other than > overriding the relevant Flux methods.

I find some different info about this, e.g. here https://github.com/JuliaLang/Pkg.jl/pull/3552 That's why I added the `ext = Base.get_extension(@__MODULE__, :ParameterSchedulersFluxExt)` to the parent package. The extension would still need to define the `Schedulers` struct though, that the parent package may access when Flux is loaded.

**Comment by maximilian-gelbrecht** [comment]
Alternatively one could just define the `Schedulers` struct in the parent package and then just put the `function Flux.Optimise.apply!(opt::Scheduler, x, Δ)` in the extension, it wouldn't be a subtype of `Flux.Optimise.AbstractOptimiser` in that case anymore. The `Schedulers` then might be useless when Flux is not loaded, but the dependency would be gone and it would avoid defining a new symbol in the extension.

**Comment by darsnack** [comment]
> The test does load Flux though, in the same place as before that didn't change, or am I misunderstanding?

You're right. I was just looking at the diff, so my mistake.

> Alternatively one could just define the Schedulers struct in the parent package and then just put the function Flux.Optimise.apply!(opt::Scheduler, x, Δ) in the extension, it wouldn't be a subtype of Flux.Optimise.AbstractOptimiser in that case anymore.

As written, we need to subtype `Flux.Optimise.AbstractOptimiser` to hit the correct methods in Flux (e.g. [these lines](https://github.com/FluxML/Flux.jl/blob/cfc6dad74c284a2d7075408651b50c13332e93f7/src/optimise/train.jl#L8-L33)).

What if you just don't export `Scheduler`, but otherwise keep it the same. Based on the Julia issue linked, I don't see why what you're doing shouldn't work otherwise.

**Comment by maximilian-gelbrecht** [comment]
Unfortunately it's not as easy as just removing the `export`. This doesn't change anything, I tried it briefly. I'll try to find some time next week and look deeper into it. It will also be a good practice to understand the extension system better.

**Comment by maximilian-gelbrecht** [comment]
I close this PR because I realised that a) the current attempt doesn't work b) it is officially not recommended to use extensions like that, symbols defined in the extension are supposed be accessed by other libraries / exported. 

Ideally, a new attempt would just remove the Flux dependency by adjusting the package to use `Optimisers`, but I guess this also in turn depends on Flux actually using Optimisers. I didn't follow Flux' development in detail in the last month, was this change now made?

**Comment by ToucheSir** [comment]
Flux has been using Optimisers.jl for a while now. We just haven't formally deprecated or removed the old style optimizers yet.

**Comment by darsnack** [comment]
Maybe we should remove support for them in auxiliary libraries like this though? "Support" doesn't mean it is not possible to use them, it is just less convenient.

I suggest a patch release now that adds a dep warning then a breaking release with #34 or some variant. That will also make the whole extension issue moot.

**Pull request closed without merging**
